### ISSUE TITLE
get r type instruction

### ISSUE THREAD

**Issue by natefrank48** [natefrank48/programming2#1]
a method that takes an instruction name and the binary instruction and returns a string of the instruction for R-type instructions

**Comment by abesisu** [comment]
Ex: ADD X14, X7, X22
R type instructions have an 11 bit opcode, 5 bit Rm (X22), 6 bit shamt, 5 bit Rn (X7), 5 bit Rd (X14)

LSL: This instruction uses the shamt field to encode the shift amount, while Rm is unused.
LSR: Same as LSL.
<img width="336" alt="Screenshot 2022-11-29 at 10 42 05 AM" src="https://user-images.githubusercontent.com/75849177/204589616-08d837e8-c19c-4a7e-9735-d07e2b3f555b.png">

BR: The branch target is encoded in the Rn field.

PRNT: This is an added instruction (part of our emulator, but not part of LEG or ARM) that prints a register name and its contents in hex and decimal.  This is an R instruction.  The opcode is 11111111101.  The register is given in the Rd field.
PRNL: This is an added instruction that prints a blank line.  This is an R instruction.  The opcode is 11111111100.
DUMP: This is an added instruction that displays the contents of all registers and memory, as well as the disassembled program.  This is an R instruction.  The opcode is 11111111110.
HALT: This is an added instruction that triggers a DUMP and terminates the emulator.  This is an R instruction.  The opcode is 11111111111
